[containers]
userns = "keep-id"
log_driver = "k8s-file"

[engine]
cgroup_manager = "cgroupfs"
runtime_supports_nocgroups = ["crun", "crun-vm", "krun", "runsc"]

[engine.runtimes]
runsc = ["/usr/local/bin/runsc-ignore-cgroups"]